variables:
    GIT_SUBMODULE_STRATEGY: recursive


build_flatpak:
    image: registry.gitlab.com/robozman/libremsonic/libremsonic/build:latest
    script:
      - cd flatpak
      - ./flatpak_build.sh
