image: archlinux
packages:
  - dbus
  - gobject-introspection
  - gtk3
  - mpv
  - python-cairo
  - python-gobject
  - python-poetry
  - xorg-server-xvfb
sources:
  - https://git.sr.ht/~sumner/sublime-music
environment:
  REPO_NAME: sublime-music
triggers:
  - action: email
    condition: failure
    to: ~sumner/sublime-music-devel@lists.sr.ht
tasks:
  - setup: |
      cd ${REPO_NAME}
      poetry install
      echo "cd ${REPO_NAME}" >> ~/.buildenv
      echo "source $(poetry env info -p)/bin/activate" >> ~/.buildenv

  - lint: |
      python setup.py check -mrs
      black --check .
      flake8
      mypy sublime tests/**/*.py
      cicd/custom_style_check.py

  - test: |
      Xvfb :119 -screen 0 1024x768x16 &
      export DISPLAY=:119
      pytest

  - build: |
      python setup.py sdist

  - build-flatpak: |
      cd ${REPO_NAME}/flatpak
      # REPO=repo ./flatpak_build.sh

  - deploy-pypi: |
      ./cicd/run_if_tagged_with_version                             \
        "twine upload -r testpypi dist/*"                           \
        "twine upload dist/*"

  - verify-pypi: |
      ./cicd/run_if_tagged_with_version                             \
        "pip install ${REPO_NAME}"
